routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index');

    Route::group(['middleware' => ['auth', 'admin']], function () {
        Route::resource('user', 'UserController');
        Route::resource('kabupaten', 'KabupatenController');
        Route::resource('kecamatan', 'KecamatanController');
        Route::resource('kelurahan', 'KelurahanController');
        Route::resource('tps', 'TpsController');
        Route::resource('paslon', 'PaslonController');
        Route::resource('suara', 'SuaraController');
        Route::resource('saksi', 'SaksiController');
        Route::resource('perhitungan', 'PerhitunganController');
        Route::resource('setup', 'SetupController');
        Route::resource('setting', 'SettingController');

        Route::get('/datakecamatan', 'KecamatanController@data');

        Route::get('/formuploadkelurahan', 'KelurahanController@form')->name('kelurahan.formupload');
        Route::post('/uploadkeluarahan', 'KelurahanController@upload')->name('kelurahan.upload');

        Route::get('/formuploadsaksi', 'SaksiController@form')->name('saksi.formupload');
        Route::post('/uploadsaksi', 'SaksiController@upload')->name('saksi.upload');

        Route::get('/generate', 'TpsController@generate')->name('tps.generate');
        Route::post('/generateapplay', 'TpsController@generateapplay')->name('tps.generateapplay');
        Route::get('/excelperhitungan', 'PerhitunganController@excel')->name('perhitungan.excel');
        Route::post('/hapus', 'PerhitunganController@hapus')->name('perhitungan.hapus');

        Route::get('/kecamatandetai', 'KecamatanController@detail')->name('kecamatan.detail');
        Route::get('/kelurahandetai', 'KelurahanController@detail')->name('kelurahan.detail');

        Route::resource('inbox', 'InboxController');
    });



    Route::get('/unread', 'InboxController@unread')->name('inbox.unread');

    Route::get('/hasil', 'PerhitunganController@hasil')->name('perhitungan.hasil');

    Route::get('/hasilsuara', 'PerhitunganController@hasilsuara')->name('perhitungan.hasilsuara');
    Route::post('/hasilsaksi', 'PerhitunganController@saksi')->name('perhitungan.saksi');
});


Route::get('/receive', 'InboxController@receive');

app/Models/Saksi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\UsesUuid;

class Saksi extends Model
{
    use UsesUuid;
    // mengnonaktifkan incrementing
    public $incrementing = false;

    protected $table = "saksi";
    protected $fillable = [];
    protected $guarded = [];

    public function tps()
    {
        return $this->belongsTo(Tps::class, 'tps_id');
    }

    public function perhitungan()
    {
        return $this->hasMany(Perhitungan::class);
    }

    public function getSuaraAttribute()
    {
        if ($this->perhitungan) {
            return $this->perhitungan->sum('jumlah');
        }
    }

    public function getNamaTpsAttribute()
    {
        if ($this->tps) {
            return $this->tps->nama;
        }
    }
    public function getIdtpsAttribute()
    {
        if ($this->tps) {
            return $this->tps->id;
        }
    }
    public function getNamaKelurahanAttribute()
    {
        if ($this->tps) {
            return $this->tps->nama_kelurahan;
        }
    }
    public function getNamaKecamatanAttribute()
    {
        if ($this->tps) {
            return $this->tps->nama_kecamatan;
        }
    }
    public function getIdKecamatanAttribute()
    {
        if ($this->tps) {
            return $this->tps->kecamatan_id;
        }
    }

    public function getNamaKabupatenAttribute()
    {
        if ($this->tps) {
            return $this->tps->nama_kabupaten;
        }
    }
    public function getIdKabupatenAttribute()
    {
        if ($this->tps) {
            return $this->tps->id_kabupaten;
        }
    }
}

app/Http/Controllers/SaksiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Saksi;
use App\Models\User;
use App\Models\Tps;
use App\Models\Kelurahan;
use App\Models\Kecamatan;
use App\Models\Perhitungan;


use Str;
use Storage;
use Excel;

use Intervention\Image\Facades\Image;
use Illuminate\Http\Request;

class SaksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title =  "Saksi";
        $nama = request()->get('nama') ?: "";
        $nohp = request()->get('hp') ?: "";
        $status = request()->get('status') ?: "";

        $dataSaksi = Saksi::orderby('nama', 'ASC')->paginate(15);
        $route = 'saksi';

        $dataKelurahan = Kelurahan::orderBy('nama', 'ASC')->get();
        $dataKecamatan = Kecamatan::orderBy('nama', 'ASC')->get();
        $kelurahan = request()->get('kelurahan') ?: "";

        if ($kelurahan != "") {
            if ($kelurahan == "allkecamatan") {
                $kecamatan_id = Kecamatan::all()->pluck('id');
                $kelurahan_id = Kelurahan::whereIn('kecamatan_id', $kecamatan_id)->get()->pluck('id');
                $checktps = Tps::whereIn('kelurahan_id', $kelurahan_id)->get()->pluck('id');
                if ($status != "") {
                    if ($status == "sudah") {
                        $dataPerhitungan = Perhitungan::get()->pluck('saksi_id');
                        $dataSaksi = Saksi::whereIn('tps_id', $checktps)->where('nohp', 'LIKE', '%' . $nohp . '%')->where('nama', 'LIKE', '%' . $nama . '%')->whereIn('id', $dataPerhitungan)->orderby('nama', 'ASC')->paginate(15);
                    }
                    if ($status == "belum") {
                        $dataPerhitungan = Perhitungan::get()->pluck('saksi_id');
                        $dataSaksi = Saksi::whereIn('tps_id', $checktps)->where('nohp', 'LIKE', '%' . $nohp . '%')->where('nama', 'LIKE', '%' . $nama . '%')->whereNotIn('id', $dataPerhitungan)->orderby('nama', 'ASC')->paginate(15);
                    }
                    if ($status == "semua") {

                        $dataSaksi = Saksi::whereIn('tps_id', $checktps)->where('nohp', 'LIKE', '%' . $nohp . '%')->where('nama', 'LIKE', '%' . $nama . '%')->paginate(15);
                    }
                } else {

                    $dataSaksi = Saksi::whereIn('tps_id', $checktps)->where('nohp', 'LIKE', '%' . $nohp . '%')->where('nama', 'LIKE', '%' . $nama . '%')->paginate(15);
                }
            } else {
                // $kelurahan;
                $checkkecamatan = Kecamatan::find($kelurahan);
                if ($checkkecamatan) {
                    $kelurahan_id = Kelurahan::where('kecamatan_id', $kelurahan)->get()->pluck('id');;
                } else {
                    $kelurahan_id = [$kelurahan];
                }
                $checktps = Tps::whereIn('kelurahan_id', $kelurahan_id)->get()->pluck('id');
                if ($status != "") {
                    if ($status == "sudah") {
                        $dataPerhitungan = Perhitungan::get()->pluck('saksi_id');
                        $dataSaksi = Saksi::whereIn('tps_id', $checktps)->where('nohp', 'LIKE', '%' . $nohp . '%')->where('nama', 'LIKE', '%' . $nama . '%')->whereIn('id', $dataPerhitungan)->orderby('nama', 'ASC')->paginate(15);
                    }
                    if ($status == "belum") {
                        $dataPerhitungan = Perhitungan::get()->pluck('saksi_id');
                        $dataSaksi = Saksi::whereIn('tps_id', $checktps)->where('nohp', 'LIKE', '%' . $nohp . '%')->where('nama', 'LIKE', '%' . $nama . '%')->whereNotIn('id', $dataPerhitungan)->orderby('nama', 'ASC')->paginate(15);
                    }
                    if ($status == "semua") {

                        $dataSaksi = Saksi::whereIn('tps_id', $checktps)->where('nohp', 'LIKE', '%' . $nohp . '%')->where('nama', 'LIKE', '%' . $nama . '%')->paginate(15);
                    }
                } else {
                    $dataSaksi = Saksi::whereIn('tps_id', $checktps)->where('nohp', 'LIKE', '%' . $nohp . '%')->where('nama', 'LIKE', '%' . $nama . '%')->paginate(15);
                }
            }
        } else {
            if ($status != "") {
                if ($status == "sudah") {
                    $dataPerhitungan = Perhitungan::get()->pluck('saksi_id');
                    $dataSaksi = Saksi::where('nohp', 'LIKE', '%' . $nohp . '%')->where('nama', 'LIKE', '%' . $nama . '%')->whereIn('id', $dataPerhitungan)->orderby('nama', 'ASC')->paginate(15);
                }
                if ($status == "belum") {
                    $dataPerhitungan = Perhitungan::get()->pluck('saksi_id');
                    $dataSaksi = Saksi::where('nohp', 'LIKE', '%' . $nohp . '%')->where('nama', 'LIKE', '%' . $nama . '%')->whereNotIn('id', $dataPerhitungan)->orderby('nama', 'ASC')->paginate(15);
                }
                if ($status == "semua") {

                    $dataSaksi = Saksi::where('nohp', 'LIKE', '%' . $nohp . '%')->where('nama', 'LIKE', '%' . $nama . '%')->paginate(15);
                }
            } else {

                $dataSaksi = Saksi::where('nohp', 'LIKE', '%' . $nohp . '%')->where('nama', 'LIKE', '%' . $nama . '%')->paginate(15);
            }
        }
        return view('saksi.index', compact(
            "title",
            "dataSaksi",
            "nama",
            "nohp",
            "status",
            "kelurahan",
            "dataKelurahan",
            "dataKecamatan",
            "route"
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title =  "Saksi";
        $route = 'saksi';
        $dataTps = Tps::orderBy('nama', 'ASC')->get();
        $action = route('saksi.store');

        return view('saksi.create', compact(
            "title",
            "action",
            "dataTps"
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute tidak boleh sama dengan data yang terdahulu',
            'same' => 'Password dan konfirmasi password harus sama',
            'max' => ':attribute maksimal 13',
            'min' => ':attribute minimal 10',
        ];

        $this->validate(request(), [
            'nik' => 'required|unique:saksi',
            'nama' => 'required',
            'alamat' => 'required',
            'nohp' => 'required|unique:saksi|max:13|min:10',
            'tps_id' => 'required|unique:saksi',

        ], $messages);

        $nama = $request->nama;
        $slug = Str::slug($nama, '-');
        $foto = $request->foto;

        $saksi = new Saksi;
        $saksi->nik =  $request->nik;
        $saksi->nama =  $nama;
        $saksi->nohp =  $request->nohp;
        $saksi->alamat =  $request->alamat;
        $saksi->tps_id =  $request->tps_id;

        if ($foto) {
            $this->validate(request(), [
                'foto' => 'mimes:jpeg,bmp,png,jpg'
            ], $messages);

            $nama_gambar = $slug . '.' . $foto->getClientOriginalExtension();

            if (!Storage::disk('public')->exists('saksi')) {
                Storage::disk('public')->makeDirectory('saksi');
            }

            $path = public_path('storage/saksi/' . $nama_gambar);

            $gambar_original = Image::make($foto)->resize(720, 720)->save($path);
            Storage::disk('public')->put('saksi/' . $nama_gambar, $gambar_original);

            if (!Storage::disk('public')->exists('saksi/thumbnail')) {
                Storage::disk('public')->makeDirectory('saksi/thumbnail');
            }
            $thumbnail = Image::make($foto)->resize(360, 360)->save($path);
            Storage::disk('public')->put('saksi/thumbnail/' . $nama_gambar, $thumbnail);
        } else {
            $nama_gambar = NULL;
        }
        $saksi->foto = $nama_gambar;

        $saksi->save();
        $userexsis = User::where('name', 'LIKE', '%' . $nama . '%')->first();
        if ($userexsis) {
            $nama = $nama . " saksi";
        }
        $user = new User;
        $user->name = $nama;
        $user->username = $request->nohp;
        $user->email = str_replace(' ', '', $nama) . '@gmail.com';
        $user->password = bcrypt($request->nohp);
        $user->rule = 2;
        $user->saksi_id = $saksi->id;
        $user->save();
        return redirect()->route('saksi.index')->with('message', 'Saksi berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Saksi  $saksi
     * @return \Illuminate\Http\Response
     */
    public function show(Saksi $saksi)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Saksi  $saksi
     * @return \Illuminate\Http\Response
     */
    public function edit(Saksi $saksi)
    {
        $title =  "Saksi";
        $route = 'saksi';
        $dataTps = Tps::orderBy('nama', 'ASC')->get();
        $action = route('saksi.update', $saksi->id);

        return view('saksi.edit', compact(
            "title",
            "action",
            "dataTps",
            "saksi"
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Saksi  $saksi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Saksi $saksi)
    {
        $messages = [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute tidak boleh sama dengan data yang terdahulu',

resources/views/saksi/create.blade.php
@extends('template.app')

@section('content')

<div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tambah {{$title}}</h3>
                </div>
                <!-- /.card-header -->
                <form action="{{ $action }}" method="post" role="form" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="card-body">
                        <div class="form-group ">
                            <label for="tps">TPS</label>
                            <select name="tps_id" class="selected2 form-control" id="cmbtps">
                                <option value="">--Pilih TPS--</option>
                                @foreach ($dataTps as $tps)
                                <option value="{{$tps->id}}" {{old('tps_id') == $tps->id ? "selected" : ""}}>{{'No TPS : '.$tps->nama.', Kelurahan : '.$tps->nama_kelurahan.', Kecamatan : '.$tps->nama_kecamatan.', Kabupaten : '.$tps->nama_kabupaten}}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('tps_id'))
                            <span class="text-danger">
                                <strong id="texttps_id">{{ $errors->first('tps_id')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <div>
                                <label for="nama" class=" form-control-label">Nama {{$title}}</label>
                            </div>
                            <div>
                                <input type="text" name="nama" placeholder="Nama {{$title}}" id="nama" class="form-control  {{$errors->has('nama') ? 'form-control is-invalid' : 'form-control'}}" value="{{old('nama')}}" required>
                            </div>
                            @if ($errors->has('nama'))
                            <span class="text-danger">
                                <strong id="textNama">{{ $errors->first('nama')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <div>
                                <label for="nik" class=" form-control-label">NIK {{$title}}</label>
                            </div>
                            <div>
                                <input type="text" name="nik" placeholder="NIK {{$title}}" id="nik" class="form-control  {{$errors->has('nik') ? 'form-control is-invalid' : 'form-control'}}" value="{{old('nik')}}" required>
                            </div>
                            @if ($errors->has('nik'))
                            <span class="text-danger">
                                <strong id="textnik">{{ $errors->first('nik')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <div>
                                <label for="hp" class=" form-control-label">No HP {{$title}}</label>
                            </div>
                            <div>
                                <input type="text" name="nohp" placeholder="No HP {{$title}}" id="nohp" class="form-control  {{$errors->has('nohp') ? 'form-control is-invalid' : 'form-control'}}" value="{{old('nohp')}}" required>
                            </div>
                            @if ($errors->has('nohp'))
                            <span class="text-danger">
                                <strong id="textnohp">{{ $errors->first('nohp')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <div>
                                <label for="alamat" class=" form-control-label">Alamat {{$title}}</label>
                            </div>
                            <div>
                                <input type="text" name="alamat" placeholder="Alamat {{$title}}" id="alamat" class="form-control  {{$errors->has('alamat') ? 'form-control is-invalid' : 'form-control'}}" value="{{old('alamat')}}" required>
                            </div>
                            @if ($errors->has('alamat'))
                            <span class="text-danger">
                                <strong id="textalamat">{{ $errors->first('nik')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="foto" class="control-label">Foto {{$title}}</label>
                            <input type="file" value="foto" name="foto" id="icon" class="form-control" value="{{old('foto')}}">
                        </div>
                        <div class="preview"></div>
                        <div>
                            <br>
                            @if ($errors->has('foto'))
                            <span class="text-danger">Mohon isi foto, upload foto dengan benar. File harus berekstensi JPG, PNG, BMP atau JPEG</span>
                            @endif
                        </div>

                    </div>

                    <!-- /.card-body -->
                    <div class="card-footer clearfix">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->

    @stop

    @push('script')
    <script>
        $(function() {
            $("#nama").keypress(function() {
                $("#nama").removeClass("is-invalid");
                $("#textNama").html("");
            });
            $("#nik").keypress(function() {
                $("#nik").removeClass("is-invalid");
                $("#textnik").html("");
            });
            $("#nik").inputFilter(function(value) {
                return /^\d*$/.test(value); // Allow digits only, using a RegExp
            });
            $("#nohp").inputFilter(function(value) {
                return /^\d*$/.test(value); // Allow digits only, using a RegExp
            });
            $("#nohp").keypress(function() {
                $("#nohp").removeClass("is-invalid");
                $("#textnohp").html("");
            });
            $("#alamat").keypress(function() {
                $("#alamat").removeClass("is-invalid");
                $("#textalamat").html("");
            });
            $('#cmbtps').select2({
                placeholder: '--- Pilih TPS---',
                width: '100%'
            });

            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function(e) {
                        $(".preview").html("<img src='" + e.target.result + "' width='310' id='image'>");
                    }

                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#icon").change(function() {
                readURL(this);
                $('.img-responsive').remove();
            });

            $('.close').on('click', function() {
                $('#image').remove();
            });
        });
    </script>
    @endpush

resources/views/saksi/index.blade.php
@extends('template.app')

@section('content')

<div class="container-fluid">
  <!-- Small boxes (Stat box) -->
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Daftar {{$title}}</h3>
          <a href="{{route($route.'.create')}}" class="btn btn-sm btn-primary float-right text-light">
            <i class="fa fa-plus"></i>Tambah Data
          </a>
          <a href="{{route($route.'.formupload')}}" class="btn btn-sm btn-danger float-right text-light">
            <i class="fa fa-plus"></i> Upload
          </a>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <form action="" role="form" id="form" enctype="multipart/form-data">
            <div class="row">

              <div class="col-lg-2">
                <label for="nama">Nama</label>
                <div class="input-group">
                  <input type="text" name="nama" class="form-control" id=" nama" value="{{$nama}}">
                </div>

              </div>
              <div class="col-lg-2">
                <label for="hp">No Hp</label>
                <div class="input-group">
                  <input type="text" name="hp" class="form-control" id=" hp" value="{{$nohp}}">
                </div>

              </div>
              <div class="col-lg-2">
                <label for="paslon">Status </label>
                <div class="input-group">
                  <select name="status" class="selected2 custom-select" id="cmbstatus">
                    <option value="">--Pilih Status Kirim--</option>
                    <option value="semua" {{$status == "semua" ? "selected" : ""}}>Semua</option>
                    <option value="sudah" {{$status == "sudah" ? "selected" : ""}}>Mengirim</option>
                    <option value="belum" {{$status == "belum" ? "selected" : ""}}>Belum Mengirim</option>
                  </select>
                </div>
              </div>
              <div class="col-lg-3">
                <label for="">Kecamatan dan Kelurahan</label>
                <select name="kelurahan" class="selected2 custom-select" id="cmbkelurahan">
                  <option value="">--Pilih Kelurahan--</option>
                  <option value="allkecamatan" {{$kelurahan == "allkecamatan" ? "selected" : ""}}>Semua Kecamatan & Kelurahan</option>
                  @foreach ($dataKelurahan as $item)
                  <option value="{{$item->id}}" {{$kelurahan == $item->id ? "selected" : ""}}>{{'Kecamatan : '.$item->nama_kecamatan.', Kelurahan : '.$item->nama}}</option>
                  @endforeach
                  @foreach ($dataKecamatan as $kecamatan)
                  <option value="{{$kecamatan->id}}" {{$kelurahan == $kecamatan->id ? "selected" : ""}}>{{'Kecamatan : '.$kecamatan->nama}}</option>
                  @endforeach
                </select>
              </div>

              <div class="col-lg-3">
                <label for="">Aksi</label>
                <div class="input-group">


                  <button type="submit" class="btn btn-warning">
                    <span class="fa fa-search"></span>
                    Cari
                  </button>
                </div>
              </div>
            </div>
          </form>
          <br>
          <table class="table table-bordered table-responsive">
            <thead>
              <tr>
                <th>No</th>
                <th>NIK</th>
                <th>No Hp</th>
                <th>Nama</th>
                <th>Kelurahan</th>
                <th>Kecamatan</th>
                <th>Kabupaten</th>
                <th>TPS</th>
                <th>Jumlah</th>
                <th>Status</th>
                <th class="text-center" width="20%">Aksi</th>
              </tr>
            </thead>
            <tbody>
              @forelse ($dataSaksi as $index => $item)

              <tr>
                <td>{{ $index+1+(($dataSaksi->CurrentPage()-1)*$dataSaksi->PerPage()) }}</td>
                <td>{{$item->nik}}</td>
                <td>{{$item->nohp}}</td>
                <td>{{$item->nama}}</td>
                <td>{{$item->nama_kelurahan}} </td>
                <td>{{$item->nama_kecamatan}} </td>
                <td>{{$item->nama_kabupaten}} </td>
                <td>{{$item->nama_tps}} </td>
                <td>
                  @forelse($item->perhitungan as $value)
                  {{ $loop->first ? '' : ', ' }}
                  No Urut {{$value->nourut}} Jumlah {{$value->jumlah}}
                  @empty
                  @endforelse
                </td>
                <td>
                  @forelse($item->perhitungan as $key => $value)
                  @if ($key == 0)
                  <span class="badge bg-primary">Sudah Mengirim</span>
                  @endif
                  @empty
                  <span class="badge bg-danger">Belum Mengirim</span>
                  @endforelse
                </td>
                <td class="text-center">
                  <a href="{{route($route.'.edit',$item->id)}}" class="btn btn-sm btn-warning text-light">
                    <i class="nav-icon fas fa-edit"></i> Ubah</a>
                  <form id="form-{{$item->id}}" action="{{ route($route.'.destroy', $item->id)}}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                    {{method_field('DELETE')}}
                  </form>
                  <button class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Hapus" onclick=deleteconf("{{$item->id}}")>
                    <i class="fa fa-trash"></i> Hapus
                  </button>
                </td>
              </tr>
              @empty
              <tr>
                <td colspan="11">Data {{$title}} tidak ada</td>
              </tr>
              @endforelse
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
        <div class="card-footer clearfix">
          {{ $dataSaksi->appends(request()->input())->links() }}
        </div>
      </div>
      <!-- ./col -->
    </div>
    <!-- /.row -->
    <!-- Main row -->
    <!-- /.row (main row) -->
  </div><!-- /.container-fluid -->

  @stop

  @push('script')
  <script>
    $('#cmbkelurahan').select2({
      placeholder: '--- Pilih Kecamatan---',
      width: '100%'
    });
    $('#cmbstatus').select2({
      placeholder: '--- Pilih Status---',
      width: '100%'
    });
  </script>
  @endpush