routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index');

    Route::group(['middleware' => ['auth', 'admin']], function () {
        Route::resource('user', 'UserController');
        Route::resource('kabupaten', 'KabupatenController');
        Route::resource('kecamatan', 'KecamatanController');
        Route::resource('kelurahan', 'KelurahanController');
        Route::resource('tps', 'TpsController');
        Route::resource('paslon', 'PaslonController');
        Route::resource('suara', 'SuaraController');
        Route::resource('saksi', 'SaksiController');
        Route::resource('perhitungan', 'PerhitunganController');
        Route::resource('setup', 'SetupController');
        Route::resource('setting', 'SettingController');

        Route::get('/datakecamatan', 'KecamatanController@data');

        Route::get('/formuploadkelurahan', 'KelurahanController@form')->name('kelurahan.formupload');
        Route::post('/uploadkeluarahan', 'KelurahanController@upload')->name('kelurahan.upload');

        Route::get('/formuploadsaksi', 'SaksiController@form')->name('saksi.formupload');
        Route::post('/uploadsaksi', 'SaksiController@upload')->name('saksi.upload');

        Route::get('/generate', 'TpsController@generate')->name('tps.generate');
        Route::post('/generateapplay', 'TpsController@generateapplay')->name('tps.generateapplay');
        Route::get('/excelperhitungan', 'PerhitunganController@excel')->name('perhitungan.excel');
        Route::post('/hapus', 'PerhitunganController@hapus')->name('perhitungan.hapus');

        Route::get('/kecamatandetai', 'KecamatanController@detail')->name('kecamatan.detail');
        Route::get('/kelurahandetai', 'KelurahanController@detail')->name('kelurahan.detail');

        Route::resource('inbox', 'InboxController');
    });



    Route::get('/unread', 'InboxController@unread')->name('inbox.unread');

    Route::get('/hasil', 'PerhitunganController@hasil')->name('perhitungan.hasil');

    Route::get('/hasilsuara', 'PerhitunganController@hasilsuara')->name('perhitungan.hasilsuara');
    Route::post('/hasilsaksi', 'PerhitunganController@saksi')->name('perhitungan.saksi');
});


Route::get('/receive', 'InboxController@receive');

resources/views/template/app.blade.php
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title> {{ucfirst($title)}}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Favicon -->
  <link rel="icon" type="image/png" href="{{'template/dist/img/logo2.png'}}" />
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('template/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{{asset('template/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{{asset('template/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{{asset('template/plugins/jqvmap/jqvmap.min.css')}}">
  <link rel="stylesheet" href="{{asset('template/plugins/sweetalert2/sweetalert2.css')}}">
  <link rel="stylesheet" href="{{asset('template/plugins/select2/css/select2.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('template/dist/css/adminlte.min.css')}}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{asset('template/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{asset('template/plugins/daterangepicker/daterangepicker.css')}}">
  <!-- summernote -->
  <link rel="stylesheet" href="{{asset('template/plugins/summernote/summernote-bs4.css')}}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  @stack('style')
</head>

<body class="hold-transition sidebar-mini  sidebar-collapse layout-fixed">
  <div class="wrapper">

    <!-- Navbar -->
    @include('template.header')
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    @include('template.menu')

    <!-- Content Wrapper. Contains page content -->

    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">{{ucfirst($title)}}</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Beranda</a></li>
                <li class="breadcrumb-item active">{{ucfirst($title)}}</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->
      @if (session('message'))
      <div class="row">
        <div class=" container-fluid alert alert-warning alert-dismissible fade show" role="alert">
          {{ session('message') }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
      @endif
      <!-- Main content -->
      <section class="content">
        @yield('content')

      </section>
      <!-- /.content -->
    </div>

    <!-- /.content-wrapper -->
    @include('template.footer')

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
  </div>
  <!-- ./wrapper -->

  <!-- jQuery -->

  <script src="{{asset('template/plugins/jquery/jquery.min.js')}}"></script>
  <!-- jQuery UI 1.11.4 -->
  <script src="{{asset('template/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->

  <script src="{{asset('template/plugins/sweetalert2/sweetalert2.all.min.js')}}"></script>
  <script>
    $.widget.bridge('uibutton', $.ui.button)
  </script>
  <!-- Bootstrap 4 -->
  <script src="{{asset('template/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <!-- ChartJS -->
  <script src="{{asset('template/plugins/chart.js/Chart.min.js')}}"></script>
  @stack('chart')
  <!-- Sparkline -->
  <script src="{{asset('template/plugins/sparklines/sparkline.js')}}"></script>
  <!-- JQVMap -->
  <script src="{{asset('template/plugins/jqvmap/jquery.vmap.min.js')}}"></script>
  <script src="{{asset('template/plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script>
  <script src="{{asset('template/plugins/select2/js/select2.full.min.js')}}"></script>
  <!-- jQuery Knob Chart -->
  <script src="{{asset('template/plugins/jquery-knob/jquery.knob.min.js')}}"></script>
  <!-- daterangepicker -->
  <script src="{{asset('template/plugins/moment/moment.min.js')}}"></script>
  <script src="{{asset('template/plugins/daterangepicker/daterangepicker.js')}}"></script>
  <!-- Tempusdominus Bootstrap 4 -->
  <script src="{{asset('template/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
  <!-- Summernote -->
  <script src="{{asset('template/plugins/summernote/summernote-bs4.min.js')}}"></script>
  <!-- overlayScrollbars -->
  <script src="{{asset('template/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
  <!-- AdminLTE App -->
  <script src="{{asset('template/dist/js/adminlte.js')}}"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  {{-- <script src="{{asset('template/dist/js/pages/dashboard.js')}}"></script> --}}
  <!-- AdminLTE for demo purposes -->
  <script src="{{asset('template/dist/js/demo.js')}}"></script>
  <script src="{{ asset('js/swall.js') }}"></script>
  <script>
    setTimeout(function() {
      $(".alert").alert('close');

    }, 6000);



    $(function() {
      function getinbox() {
        $.ajax({
          type: 'get',
          url: "{{route('inbox.unread')}}",
          headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          },
          success: function(data) {
            var jumlah = data.jumlah;
            var data = data.data;
            // var template = $('#dataInbox').html();

            var content = '';
            $('#countinbox').html(jumlah);
            $('#topcountinbox').html(jumlah);
            $.each(data, function() {
              content += ` <a href="/inbox/${this.id}" class="dropdown-item">
              <!-- Message Start -->
              <div class="media">
                <div class="media-body">
                  <h3 class="dropdown-item-title">
                    ${this.sender}
                    <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                  </h3>
                  <p class="text-sm">${this.content}</p>
                  <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> ${this.time}</p>
                </div>
              </div>
            </a>`;
              $(".dataInbox").html(content);
            });


          }
        });
      }
      // getinbox();

      setInterval(function() {
        // getinbox();
      }, 6000);
    });
    (function($) {
      $.fn.inputFilter = function(inputFilter) {
        return this.on("input keydown keyup mousedown mouseup select contextmenu drop", function() {
          if (inputFilter(this.value)) {
            this.oldValue = this.value;
            this.oldSelectionStart = this.selectionStart;
            this.oldSelectionEnd = this.selectionEnd;
          } else if (this.hasOwnProperty("oldValue")) {
            this.value = this.oldValue;
            this.setSelectionRange(this.oldSelectionStart, this.oldSelectionEnd);
          } else {
            this.value = "";
          }
        });
      };
    }(jQuery));
  </script>

  @stack('script')
</body>

</html>

resources/views/template/footer.blade.php
<footer class="main-footer">
  <strong>Copyright &copy; 2019-2020 <a href="http://www.borneocorner.com/">Borneo Corner</a>.</strong>
  All rights reserved.
  <div class="float-right d-none d-sm-inline-block">
    <b>Version</b> 3.0.0-rc.3
  </div>
</footer>

resources/views/template/header.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
    </li>
  </ul>

  <!-- SEARCH FORM -->


  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">

    <li class="nav-item dropdown">
      <!-- <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge" id="topcountinbox"></span>
      </a> -->
      <!-- <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <div class="dataInbox">

          <a href="" class="dropdown-item">

            <div class="media">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  <span id="sender"></span>
                  <span class="float-right text-sm text-danger"></span>
                </h3>
                <p class="text-sm" id="pesan"></p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
          </a>
          <div class="dropdown-divider"></div>
        </div>
        <a href="{{route('inbox.index')}}" class="dropdown-item dropdown-footer">See All Messages</a>
      </div> -->
    </li>


  </ul>
</nav>

resources/views/template/menu.blade.php
<aside class="main-sidebar sidebar-collapse sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="{{route('home')}}" class="brand-link">
    <img src="{{asset('template/dist/img/logo2.png')}}" width="30%" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">Dashboard</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <!-- <img src="{{asset('template/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image"> -->
      </div>
      <div class="info">
        <a href="#" class="d-block">{{ucfirst(Auth::user()->name)}}</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class  with font-awesome or any other icon font library -->
        <li class="nav-item">
          <a href="{{route('home')}}" class="nav-link {{ Request::is('/') ? 'active' : '' }}">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              Dashboard
            </p>
          </a>
        </li>
        @if(Auth::user()->rule == 1)
        <li class="nav-item has-treeview {{ Request::segment(1) === 'kabupaten' ? 'menu-open' : '' }} {{ Request::segment(1) === 'kelurahan' ? 'menu-open' : '' }} {{ Request::segment(1) === 'kecamatan' ? 'menu-open' : '' }}">
          <a href="#" class="nav-link {{ Request::segment(1) === 'kabupaten' ? 'active' : '' }} {{ Request::segment(1) === 'kelurahan' ? 'active' : '' }} {{ Request::segment(1) === 'kecamatan' ? 'active' : '' }}">
            <i class="nav-icon fa fa-building"></i>
            <p>
              Data Wilayah
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{{route('kabupaten.index')}}" class="nav-link {{ Request::segment(1) === 'kabupaten' ? 'active' : '' }}">
                <i class="nav-icon fa fa-building"></i>
                <p>
                  Kabupaten
                  <!-- <span class="right badge badge-danger">New</span> -->
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{route('kecamatan.index')}}" class="nav-link {{ Request::segment(1) === 'kecamatan' ? 'active' : '' }}">
                <i class="nav-icon fa fa-briefcase"></i>
                <p>
                  Kecamatan
                  <!-- <span class="right badge badge-danger">New</span> -->
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{{route('kelurahan.index')}}" class="nav-link {{ Request::segment(1) === 'kelurahan' ? 'active' : '' }}">
                <i class="nav-icon fas fa-map"></i>
                <p>
                  Kelurahan
                  <!-- <span class="right badge badge-danger">New</span> -->
                </p>
              </a>
            </li>
          </ul>
        </li>

        <li class="nav-item">
          <a href="{{route('tps.index')}}" class="nav-link {{ Request::segment(1) === 'tps' ? 'active' : '' }}">
            <i class="nav-icon fas fa-archway"></i>
            <p>
              TPS
              <!-- <span class="right badge badge-danger">New</span> -->
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{route('paslon.index')}}" class="nav-link {{ Request::segment(1) === 'paslon' ? 'active' : '' }}">
            <i class="nav-icon fas fa-address-card"></i>
            <p>
              Paslon
              <!-- <span class="right badge badge-danger">New</span> -->
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{route('suara.index')}}" class="nav-link {{ Request::segment(2) === 'suara?suara=tidak' ? 'active' : '' }}">
            <i class="nav-icon fas fa-balance-scale"></i>
            <p>
              Suara
              <!-- <span class="right badge badge-danger">New</span> -->
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{route('saksi.index')}}" class="nav-link {{ Request::segment(1) === 'saksi' ? 'active' : '' }}">
            <i class="nav-icon fas fa-address-book"></i>
            <p>
              Saksi
              <!-- <span class=" right badge badge-danger">New</span> -->
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{route('perhitungan.index')}}" class="nav-link {{ Request::segment(1) === 'perhitungan' ? 'active' : '' }}">
            <i class="nav-icon fas fa-book-reader"></i>
            <p>
              Perhitungan
              <!-- <span class="right badge badge-danger">New</span> -->
            </p>
          </a>
        </li>
        <!-- <li class="nav-item">
          <a href="{{route('inbox.index')}}" class="nav-link {{ Request::segment(1) === 'inbox' ? 'active' : '' }}">
            <i class="nav-icon fa fa-envelope"></i>
            <p>
              SMS
              <span class="badge badge-info right" id="countinbox"></span>
            </p>
          </a>
        </li> -->
        <li class="nav-item">
          <a href="{{route('setting.index')}}" class="nav-link {{ Request::segment(1) === 'setting' ? 'active' : '' }}">
            <i class="nav-icon fa fa-cog"></i>
            <p>
              Setting
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{route('user.index')}}" class="nav-link {{ Request::segment(1) === 'user' ? 'active' : '' }}">
            <i class="nav-icon fa fa-user-circle"></i>
            <p>
              Pengguna
              <!-- <span class="right badge badge-danger">New</span> -->
            </p>
          </a>
        </li>
        @endif
        <!-- <li class="nav-item">
          <a href="{{route('setup.index')}}" class="nav-link {{ Request::segment(1) === 'setup' ? 'active' : '' }}">
            <i class="nav-icon fas fa-cogs"></i>
            <p>
              Setup
             
            </p>
          </a>
        </li> -->

        <li class="nav-item">
          <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
            <i class="nav-icon fa fa-power-off"></i>
            <p>
              Keluar
              <!-- <span class="right badge badge-danger">New</span> -->
            </p>
          </a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
          </form>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>