routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index');

    Route::group(['middleware' => ['auth', 'admin']], function () {
        Route::resource('user', 'UserController');
        Route::resource('kabupaten', 'KabupatenController');
        Route::resource('kecamatan', 'KecamatanController');
        Route::resource('kelurahan', 'KelurahanController');
        Route::resource('tps', 'TpsController');
        Route::resource('paslon', 'PaslonController');
        Route::resource('suara', 'SuaraController');
        Route::resource('saksi', 'SaksiController');
        Route::resource('perhitungan', 'PerhitunganController');
        Route::resource('setup', 'SetupController');
        Route::resource('setting', 'SettingController');

        Route::get('/datakecamatan', 'KecamatanController@data');

        Route::get('/formuploadkelurahan', 'KelurahanController@form')->name('kelurahan.formupload');
        Route::post('/uploadkeluarahan', 'KelurahanController@upload')->name('kelurahan.upload');

        Route::get('/formuploadsaksi', 'SaksiController@form')->name('saksi.formupload');
        Route::post('/uploadsaksi', 'SaksiController@upload')->name('saksi.upload');

        Route::get('/generate', 'TpsController@generate')->name('tps.generate');
        Route::post('/generateapplay', 'TpsController@generateapplay')->name('tps.generateapplay');
        Route::get('/excelperhitungan', 'PerhitunganController@excel')->name('perhitungan.excel');
        Route::post('/hapus', 'PerhitunganController@hapus')->name('perhitungan.hapus');

        Route::get('/kecamatandetai', 'KecamatanController@detail')->name('kecamatan.detail');
        Route::get('/kelurahandetai', 'KelurahanController@detail')->name('kelurahan.detail');

        Route::resource('inbox', 'InboxController');
    });



    Route::get('/unread', 'InboxController@unread')->name('inbox.unread');

    Route::get('/hasil', 'PerhitunganController@hasil')->name('perhitungan.hasil');

    Route::get('/hasilsuara', 'PerhitunganController@hasilsuara')->name('perhitungan.hasilsuara');
    Route::post('/hasilsaksi', 'PerhitunganController@saksi')->name('perhitungan.saksi');
});


Route::get('/receive', 'InboxController@receive');

app/Models/Tps.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Traits\UsesUuid;

class Tps extends Model
{
    use UsesUuid;
    // mengnonaktifkan incrementing
    public $incrementing = false;

    protected $table = "tps";
    protected $fillable = [];
    protected $guarded = [];

    public function kelurahan()
    {
        return $this->belongsTo(Kelurahan::class, 'kelurahan_id');
    }

    public function getNamaKelurahanAttribute()
    {
        if ($this->kelurahan) {
            return $this->kelurahan->nama;
        }
    }
    public function getIdKelurahanAttribute()
    {
        if ($this->kelurahan) {
            return $this->kelurahan->id;
        }
    }
    public function getNamaKecamatanAttribute()
    {
        if ($this->kelurahan) {
            return $this->kelurahan->nama_kecamatan;
        }
    }
    public function getIdKecamatanAttribute()
    {
        if ($this->kelurahan) {
            return $this->kelurahan->kecamatan_id;
        }
    }

    public function getNamaKabupatenAttribute()
    {
        if ($this->kelurahan) {
            return $this->kelurahan->nama_kabupaten;
        }
    }
    public function getIdKabupatenAttribute()
    {
        if ($this->kelurahan) {
            return $this->kelurahan->id_kabupaten;
        }
    }
}

app/Http/Controllers/TpsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tps;
use App\Models\Kelurahan;
use App\Models\Kabupaten;
use App\Models\Kecamatan;
use Illuminate\Http\Request;

class TpsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title =  "Tps";
        $dataTps = Tps::orderBy('kelurahan_id', 'ASC')->orderBy('nama', 'ASC')->paginate(10);
        $route = 'tps';

        $limit = request()->get('limit') ?: "";
        $kelurahan = request()->get('kelurahan') ?: "";
        $nama = request()->get('nama') ?: "";

        $dataKelurahan = Kelurahan::orderBy('nama', 'ASC')->get();
        $dataKecamatan = Kecamatan::orderBy('nama', 'ASC')->get();

        if ($nama == "all" || $nama == "") {
            if ($kelurahan != "") {
                if ($kelurahan == "allkecamatan") {
                    $kecamatan_id = Kecamatan::all()->pluck('id');
                    $kelurahan_id = Kelurahan::whereIn('kecamatan_id', $kecamatan_id)->get()->pluck('id');
                    $dataTps = Tps::whereIn('kelurahan_id', $kelurahan_id)->orderBy('nama', 'ASC')->paginate(15);
                } else {
                    $checkkelurahan = Kelurahan::find($kelurahan);
                    if (!$checkkelurahan) {
                        $kecamatan_id = Kecamatan::find($kelurahan);
                        $kelurahan_id = Kelurahan::whereIn('kecamatan_id', $kecamatan_id)->get()->pluck('id');
                        $dataTps = Tps::where('kelurahan_id', $kelurahan_id)->orderBy('nama', 'ASC')->paginate(15);
                    } else {
                        $kelurahan_id = $checkkelurahan->id;
                        $dataTps = Tps::where('kelurahan_id', $kelurahan_id)->orderBy('nama', 'ASC')->paginate(15);
                    }
                }
            }
        } else {
            # code...
            if ($kelurahan != "") {
                if ($kelurahan == "allkecamatan") {
                    $kecamatan_id = Kecamatan::all()->pluck('id');
                    $kelurahan_id = Kelurahan::whereIn('kecamatan_id', $kecamatan_id)->get()->pluck('id');
                    $dataTps = Tps::where('nama', "like", "%" . $nama . "%")->orderBy('nama', 'ASC')->whereIn('kelurahan_id', $kelurahan_id)->paginate(15);
                } else {
                    $checkkelurahan = Kelurahan::find($kelurahan);
                    if (!$checkkelurahan) {
                        $kecamatan_id = Kecamatan::find($kelurahan);
                        $kelurahan_id = Kelurahan::whereIn('kecamatan_id', $kecamatan_id)->get()->pluck('id');
                        $dataTps = Tps::where('nama', "like", "%" . $nama . "%")->where('kelurahan_id', $kelurahan_id)->orderBy('nama', 'ASC')->paginate(15);
                    } else {
                        $kelurahan_id = $checkkelurahan->id;
                        $dataTps = Tps::where('nama', "like", "%" . $nama . "%")->where('kelurahan_id', $kelurahan_id)->orderBy('nama', 'ASC')->paginate(15);
                    }
                }
            } else {

                $dataTps = Tps::where('nama', "like", "%" . $nama . "%")->orderBy('kelurahan_id', 'ASC')->orderBy('nama', 'ASC')->paginate(10);
            }
        }


        return view('tps.index', compact(
            "title",
            "dataTps",
            "nama",
            "dataKelurahan",
            "kelurahan",
            "dataKecamatan",
            "route"
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title =  "TPS";
        $route = 'tps';
        $dataKabupaten = Kabupaten::all();
        $dataKecamatan = Kecamatan::all();
        $dataKelurahan = Kelurahan::all();
        $action = route('tps.store');

        return view('tps.create', compact(
            "title",
            "action",
            "dataKabupaten",
            "dataKecamatan",
            "dataKelurahan"
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute tidak boleh sama dengan data yang terdahulu',
            'same' => 'Password dan konfirmasi password harus sama',
        ];

        $this->validate(request(), [
            'nama' => 'required|unique:tps,nama,' . $request->nama . ',id,kelurahan_id,' . $request->kelurahan_id,
            'kelurahan_id' => 'required|min:1',
        ], $messages);

        $tps = new Tps;
        $tps->nama =  $request->nama;
        $tps->kelurahan_id =  $request->kelurahan_id;
        $tps->save();
        return redirect()->route('tps.index')->with('message', 'TPS berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tps  $tps
     * @return \Illuminate\Http\Response
     */
    public function show(Tps $tps)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tps  $tps
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tps = Tps::find($id);
        $title =  "TPS " . $tps->nama;
        $dataKabupaten = Kabupaten::all();
        $dataKecamatan = Kecamatan::all();
        $dataKelurahan = Kelurahan::all();
        $action = route('tps.update', $tps->id);
        return view('tps.edit', compact(
            'action',
            'title',
            'tps',
            'dataKabupaten',
            "dataKecamatan",
            "dataKelurahan"
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tps  $tps
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tps = Tps::find($id);
        $messages = [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute tidak boleh sama dengan data yang terdahulu',
            'date' => ':attribute harus menggunakan tanggal yang benar',
            'date_format' => ':attribute harus menggunakan tanggal yang benar',
            'max' => ':attribute maksimal 30',
        ];

        $this->validate(request(), [
            'nama' => 'required|unique:tps,nama,' . $id . ',id,kelurahan_id,' . $request->kelurahan_id,
            'kelurahan_id' => 'required|min:1',
        ], $messages);


        $tps->nama = $request->nama;
        $tps->kelurahan_id = $request->kelurahan_id;
        $tps->save();

        return redirect()->route('tps.index')->with('message', 'Berhasil Mengubah Data TPS')->with('Class', 'Berhasil');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tps  $tps
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tps = Tps::find($id);
        $tps->delete();

        return redirect()->route('tps.index')->with('message', 'TPS berhasil dihapus')->with('Class', 'Berhasil');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function generate()
    {
        $title =  "Generate TPS";
        $route = 'tps';
        $dataKabupaten = Kabupaten::all();
        $dataKecamatan = Kecamatan::all();
        $dataKelurahan = Kelurahan::all();
        $action = route('tps.generateapplay');

        return view('tps.generate', compact(
            "title",
            "action",
            "dataKabupaten",
            "dataKecamatan",
            "dataKelurahan"
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function generateapplay(Request $request)
    {
        $messages = [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute tidak boleh sama dengan data yang terdahulu',
            'date' => ':attribute harus menggunakan tanggal yang benar',
            'date_format' => ':attribute harus menggunakan tanggal yang benar',
            'max' => ':attribute maksimal 30',
        ];

        $this->validate(request(), [
            'kelurahan_id' => 'required',
            'jumlah' => 'required|min:1',
        ], $messages);

        $kelurahan_id = $request->kelurahan_id;
        $namatps = [];
        for ($i = 0; $i < $request->jumlah; $i++) {
            # code...
            $namatps[$i] = "TPS" . str_pad($i + 1, 2, "0", STR_PAD_LEFT);
        }
        foreach ($namatps as $index => $item) {

            if ($kelurahan_id == "all") {
                $kelurahan = Kelurahan::all();

                foreach ($kelurahan as $key => $value) {
                    $tps = Tps::where('nama', $value)->where('kelurahan_id', $kelurahan_id)->first();
                    if (!$tps) {
                        $tps = new Tps;
                    }
                    $tps->nama =  $item;
                    $tps->kelurahan_id =  $value->id;
                    $tps->save();
                }
            } else {
                $tps = Tps::where('nama', $item)->where('kelurahan_id', $kelurahan_id)->first();
                if (!$tps) {
                    $tps = new Tps;
                }
                $tps->nama =  $item;
                $tps->kelurahan_id =  $kelurahan_id;
                $tps->save();
            }
        }

        return redirect()->route('tps.index')->with('message', 'Berhasil Generate TPS ' . $request->jumlah)->with('Class', 'Berhasil');
    }
}

resources/views/tps/create.blade.php
@extends('template.app')

@section('content')

<div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tambah {{$title}}</h3>
                </div>
                <!-- /.card-header -->
                <form action="{{ $action }}" method="post" role="form" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="card-body">
                        <div class="form-group ">
                            <label for="kelurahan">Kelurahan</label>
                            <select name="kelurahan_id" class="selected2 form-control" id="cmbkelurahan">
                                <option value="">--Pilih kelurahan--</option>
                                @foreach ($dataKelurahan as $kelurahan)
                                <option value="{{$kelurahan->id}}" {{old('kelurahan_id') == $kelurahan->id ? "selected" : ""}}>{{'Kelurahan : '.$kelurahan->nama.', Kecamatan : '.$kelurahan->nama_kecamatan.', Kabupaten : '.$kelurahan->nama_kabupaten}}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('kelurahan_id'))
                            <span class="text-danger">
                                <strong id="textkelurahan_id">{{ $errors->first('kelurahan_id')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <div>
                                <label for="nama" class=" form-control-label">Nama {{$title}}</label>
                            </div>
                            <div>
                                <input type="text" name="nama" placeholder="Nama {{$title}}" id="nama" class="form-control  {{$errors->has('nama') ? 'form-control is-invalid' : 'form-control'}}" value="{{old('nama')}}" required>
                            </div>
                            @if ($errors->has('nama'))
                            <span class="text-danger">
                                <strong id="textNama">{{ $errors->first('nama')}}</strong>
                            </span>
                            @endif
                        </div>

                    </div>

                    <!-- /.card-body -->
                    <div class="card-footer clearfix">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->

    @stop

    @push('script')
    <script>
        $(function() {
            $("#nama").keypress(function() {
                $("#nama").removeClass("is-invalid");
                $("#textNama").html("");
            });
            $('#cmbkabupaten').select2({
                placeholder: '--- Pilih Kabupaten---',
                width: '100%'
            });
            $('#cmbkecamatan').select2({
                placeholder: '--- Pilih Kecamatan---',
                width: '100%'
            });
            $('#cmbkelurahan').select2({
                placeholder: '--- Pilih Kelurahan---',
                width: '100%'
            });

        });
    </script>
    @endpush

resources/views/tps/edit.blade.php
@extends('template.app')

@section('content')

<div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Ubah {{$title}}</h3>
                </div>
                <!-- /.card-header -->
                <form action="{{ $action }}" method="post" role="form" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="card-body">

                        <div class="form-group ">
                            <label for="kelurahan">Kelurahan</label>
                            <select name="kelurahan_id" class="selected2 form-control" id="cmbkelurahan">
                                <option value="">--Pilih Kelurahan--</option>
                                @foreach ($dataKelurahan as $kelurahan)
                                <option value="{{$kelurahan->id}}" {{$tps->kelurahan_id == $kelurahan->id ? "selected" : ""}}>{{'Kelurahan : '.$kelurahan->nama.', Kecamatan : '.$kelurahan->nama_kecamatan.', Kabupaten : '.$kelurahan->nama_kabupaten}}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('kelurahan'))
                            <span class="text-danger">
                                <strong id="textkelurahan">{{ $errors->first('kelurahan')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <div>
                                <label for="nama" class=" form-control-label">Nama {{$title}}</label>
                            </div>
                            <div>
                                <input type="text" name="nama" id="nama" placeholder="Nama {{$title}}" class="form-control  {{$errors->has('nama') ? 'form-control is-invalid' : 'form-control'}}" value="{{ $tps->nama }}" required>
                            </div>
                            @if ($errors->has('nama'))
                            <span class="text-danger">
                                <strong id="textNama">{{ $errors->first('nama')}}</strong>
                            </span>
                            @endif
                        </div>
                    </div>


                    <!-- /.card-body -->
                    <div class="card-footer clearfix">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->

    @stop

    @push('script')
    <script>
        $(function() {
            $("#nama").keypress(function() {
                $("#nama").removeClass("is-invalid");
                $("#textNama").html("");
            });

            // $("#id_rt").keypress(function(){
            //   $("#id_rt").removeClass("is-invalid");
            //   $("#textid_rt").html("");
            // });
            $('#cmbkabupaten').select2({
                placeholder: '--- Pilih Kabupaten---',
                width: '100%'
            });
            $('#cmbkecamatan').select2({
                placeholder: '--- Pilih Kecamatan---',
                width: '100%'
            });
            $('#cmbkelurahan').select2({
                placeholder: '--- Pilih Kelurahan---',
                width: '100%'
            });
        });
    </script>
    @endpush

resources/views/tps/generate.blade.php
@extends('template.app')

@section('content')

<div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tambah {{$title}}</h3>
                </div>
                <!-- /.card-header -->
                <form action="{{ $action }}" method="post" role="form" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="card-body">
                        <div class="form-group ">
                            <label for="kelurahan">Kelurahan</label>
                            <select name="kelurahan_id" class="selected2 form-control" id="cmbkelurahan">
                                <option value="">--Pilih Kelurahan--</option>
                                <option value="all">Semua Kelurahan</option>
                                @foreach ($dataKelurahan as $kelurahan)
                                <option value="{{$kelurahan->id}}" {{old('kelurahan_id') == $kelurahan->id ? "selected" : ""}}>{{'Kelurahan : '.$kelurahan->nama.', Kecamatan : '.$kelurahan->nama_kecamatan.', Kabupaten : '.$kelurahan->nama_kabupaten}}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('kelurahan_id'))
                            <span class="text-danger">
                                <strong id="textkelurahan_id">{{ $errors->first('kelurahan_id')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <div>
                                <label for="jumlah" class=" form-control-label">Jumlah {{$title}}</label>
                            </div>
                            <div>
                                <input type="text" name="jumlah" placeholder="Jumlah {{$title}}" id="jumlah" class="form-control  {{$errors->has('jumlah') ? 'form-control is-invalid' : 'form-control'}}" value="{{old('jumlah')}}" required>
                            </div>
                            @if ($errors->has('jumlah'))
                            <span class="text-danger">
                                <strong id="textjumlah">{{ $errors->first('jumlah')}}</strong>
                            </span>
                            @endif
                        </div>

                    </div>

                    <!-- /.card-body -->
                    <div class="card-footer clearfix">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->

    @stop

    @push('script')
    <script>
        $(function() {
            $("#jumlah").keypress(function() {
                $("#jumlah").removeClass("is-invalid");
                $("#textjumlah").html("");
            });
            $("#jumlah").inputFilter(function(value) {
                return /^\d*$/.test(value); // Allow digits only, using a RegExp
            });
            $('#cmbkabupaten').select2({
                placeholder: '--- Pilih Kabupaten---',
                width: '100%'
            });
            $('#cmbkecamatan').select2({
                placeholder: '--- Pilih Kecamatan---',
                width: '100%'
            });
            $('#cmbkelurahan').select2({
                placeholder: '--- Pilih Kelurahan---',
                width: '100%'
            });
        });
    </script>
    @endpush

resources/views/tps/index.blade.php
@extends('template.app')

@section('content')

<div class="container-fluid">
  <!-- Small boxes (Stat box) -->
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Daftar {{$title}}</h3>
          <a href="{{route($route.'.create')}}" class="btn btn-sm btn-primary float-right text-light">
            <i class="fa fa-plus"></i> Tambah Data
          </a>
          <a href="{{route($route.'.generate')}}" class="btn btn-sm btn-warning float-right text-light">
            <i class="fa fa-plus"></i> Generate TPS
          </a>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <form action="" role="form" enctype="multipart/form-data">
            <div class="row">

              <div class="col-lg-3">
                <label for="nama">Nama</label>
                <div class="input-group">
                  <input type="text" name="nama" class="form-control" id=" nama" value="{{$nama}}">
                </div>

              </div>
              <div class="col-lg-3">
                <label for="nama">Nama</label>
                <div class="input-group">
                  <select name="kelurahan" class="selected2 custom-select" id="cmbkelurahan">
                    <option value="">--Pilih Kelurahan--</option>
                    <option value="allkecamatan" {{$kelurahan == "allkecamatan" ? "selected" : ""}}>Semua Kecamatan & Kelurahan</option>
                    @foreach ($dataKelurahan as $item)
                    <option value="{{$item->id}}" {{$kelurahan == $item->id ? "selected" : ""}}>{{'Kecamatan : '.$item->nama_kecamatan.', Kelurahan : '.$item->nama}}</option>
                    @endforeach
                    @foreach ($dataKecamatan as $kecamatan)
                    <option value="{{$kecamatan->id}}" {{$kelurahan == $kecamatan->id ? "selected" : ""}}>{{'Kecamatan : '.$kecamatan->nama}}</option>
                    @endforeach
                  </select>
                </div>

              </div>
              <div class="col-lg-3">
                <label for="">Aksi</label>
                <div class="input-group">


                  <button type="submit" class="btn btn-warning">
                    <span class="fa fa-search"></span>
                    Cari
                  </button>
                </div>
              </div>
            </div>
          </form>
          <table class="table table-bordered table-responsive">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Kelurahan</th>
                <th>Kecamatan</th>
                <th>Kabupaten</th>
                <th class="text-center" width="20%">Aksi</th>
              </tr>
            </thead>
            <tbody>
              @forelse ($dataTps as $index => $item)

              <tr>
                <td>{{ $index+1+(($dataTps->CurrentPage()-1)*$dataTps->PerPage()) }}</td>
                <td>{{$item->nama}}</td>
                <td>{{$item->nama_kelurahan}} </td>
                <td>{{$item->nama_kecamatan}} </td>
                <td>{{$item->nama_kabupaten}} </td>
                <td class="text-center">
                  <a href="{{route($route.'.edit',$item->id)}}" class="btn btn-sm btn-warning text-light">
                    <i class="nav-icon fas fa-edit"></i> Ubah</a>
                  <form id="form-{{$item->id}}" action="{{ route($route.'.destroy', $item->id)}}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                    {{method_field('DELETE')}}
                  </form>
                  <button class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Hapus" onclick=deleteconf("{{$item->id}}")>
                    <i class="fa fa-trash"></i> Hapus
                  </button>
                </td>
              </tr>
              @empty
              <tr>
                <td colspan="10">Data {{$title}} tidak ada</td>
              </tr>
              @endforelse
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
        <div class="card-footer clearfix">
          {{ $dataTps->appends(request()->input())->links() }}
        </div>
      </div>
      <!-- ./col -->
    </div>
    <!-- /.row -->
    <!-- Main row -->
    <!-- /.row (main row) -->
  </div><!-- /.container-fluid -->

  @stop

  @push('script')
  <script>
    $('#cmbkelurahan').select2({
      placeholder: '--- Pilih Kecamatan & Kelurahan---',
      width: '100%'
    });
  </script>
  @endpush