routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index');

    Route::group(['middleware' => ['auth', 'admin']], function () {
        Route::resource('user', 'UserController');
        Route::resource('kabupaten', 'KabupatenController');
        Route::resource('kecamatan', 'KecamatanController');
        Route::resource('kelurahan', 'KelurahanController');
        Route::resource('tps', 'TpsController');
        Route::resource('paslon', 'PaslonController');
        Route::resource('suara', 'SuaraController');
        Route::resource('saksi', 'SaksiController');
        Route::resource('perhitungan', 'PerhitunganController');
        Route::resource('setup', 'SetupController');
        Route::resource('setting', 'SettingController');

        Route::get('/datakecamatan', 'KecamatanController@data');

        Route::get('/formuploadkelurahan', 'KelurahanController@form')->name('kelurahan.formupload');
        Route::post('/uploadkeluarahan', 'KelurahanController@upload')->name('kelurahan.upload');

        Route::get('/formuploadsaksi', 'SaksiController@form')->name('saksi.formupload');
        Route::post('/uploadsaksi', 'SaksiController@upload')->name('saksi.upload');

        Route::get('/generate', 'TpsController@generate')->name('tps.generate');
        Route::post('/generateapplay', 'TpsController@generateapplay')->name('tps.generateapplay');
        Route::get('/excelperhitungan', 'PerhitunganController@excel')->name('perhitungan.excel');
        Route::post('/hapus', 'PerhitunganController@hapus')->name('perhitungan.hapus');

        Route::get('/kecamatandetai', 'KecamatanController@detail')->name('kecamatan.detail');
        Route::get('/kelurahandetai', 'KelurahanController@detail')->name('kelurahan.detail');

        Route::resource('inbox', 'InboxController');
    });



    Route::get('/unread', 'InboxController@unread')->name('inbox.unread');

    Route::get('/hasil', 'PerhitunganController@hasil')->name('perhitungan.hasil');

    Route::get('/hasilsuara', 'PerhitunganController@hasilsuara')->name('perhitungan.hasilsuara');
    Route::post('/hasilsaksi', 'PerhitunganController@saksi')->name('perhitungan.saksi');
});


Route::get('/receive', 'InboxController@receive');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Traits\UsesUuid;

class User extends Authenticatable
{
    use Notifiable, UsesUuid;

    // mengnonaktifkan incrementing
    public $incrementing = false;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Hash;
use App\Models\Saksi;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     * 
     */
    public function index()
    {
        $title =  "Pengguna";
        $dataUser = User::where('id', '!=', 1)->paginate(5);
        return view('user.index', ["title" => $title, "dataUser" => $dataUser]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title =  "Tambah Pengguna";
        $action = route('user.store');

        return view('user.create', compact("title", "action"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute tidak boleh sama',
            'same' => 'Password dan konfirmasi password harus sama',
        ];

        $this->validate(request(), [
            'name' => 'required|unique:users',
            'email' => 'required|unique:users',
            'password' => 'required|min:6',
            'passwordConfrim' => 'required|same:password|min:6',
        ], $messages);

        $pass = bcrypt(request()->input('password'));
        $name = request()->input('name');

        $user = new User;
        $user->name = $name;
        $user->username = $name;
        $user->email = request()->input('email');
        $user->password = $pass;
        $user->rule = $request->rule;
        $user->saksi_id = 1;
        $user->save();
        return redirect()->route('user.index')->with('message', 'User berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    { }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $title =  "Ubah Pengguna " . $user->nama;
        $action = route('user.update', $user->id);
        return view('user.edit', compact('action', 'title', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $messages = [
            'required' => ':attribute tidak boleh kosong',
            'unique' => ':attribute tidak boleh sama',
            'same' => ':attribute password dan confrim password harus sama',
        ];

        $this->validate(request(), [
            'name' => 'required|unique:users,name,' . $id,
            'email' => 'required|unique:users,email,' . $id
        ], $messages);

        $user = User::find($id);
        $name = request()->input('name');
        if (request()->input('passwordNew')) {
            # code...
            $pass = bcrypt(request()->input('passwordNew'));
            $user->password = $pass;
            $this->validate(request(), [
                'name' => 'required|unique:users,name,' . $id,
                'email' => 'required|unique:users,email,' . $id,
                'passwordNew' => 'required|min:6',
                'passwordConfrim' => 'required|same:passwordNew|min:6',
            ], $messages);
        }

        $user->name = $name;
        $user->username = $name;
        $user->email = request()->input('email');

        $user->rule = $request->rule;
        $user->update();

        return redirect()->route('user.index')->with('message', 'User berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        $saksi = Saksi::find($user->saksi_id);
        if ($saksi) {
            $saksi->delete();
        }
        return redirect()->route('user.index')->with('message', 'Pengguna berhasil dihapus');
    }
}

resources/views/user/create.blade.php
@extends('template.app')

@section('content')

<div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{$title}}</h3>
                </div>
                <!-- /.card-header -->
                <form action="{{ $action }}" method="post" role="form" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="card-body">
                        <div class="form-group">
                            <div>
                                <label for="Name" class=" form-control-label">Name</label>
                            </div>
                            <div>
                                <input type="text" name="name" placeholder="Name User" class="form-control  {{$errors->has('name') ? 'form-control is-invalid' : 'form-control'}}" value="{{old('name')}}" required>
                            </div>
                            @if ($errors->has('name'))
                            <span class="text-danger">
                                <strong id="textkk">{{ $errors->first('name')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <div>
                                <label for="email" class=" form-control-label">Email</label>
                            </div>
                            <div>
                                <input type="email" name="email" placeholder="Masukan Email" class="form-control  {{$errors->has('email') ? 'form-control is-invalid' : 'form-control'}}" value="{{old('email')}}" required>
                            </div>
                            @if ($errors->has('email'))
                            <span class="text-danger">
                                <strong id="textemail">{{ $errors->first('email')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <div>
                                <label for="password" class=" form-control-label">Password</label>
                            </div>
                            <div>
                                <input type="password" name="password" placeholder="Password" class="form-control  {{$errors->has('password') ? 'form-control is-invalid' : 'form-control'}}" required>
                            </div>
                            @if ($errors->has('password'))
                            <span class="text-danger">
                                <strong id="textpassword">{{ $errors->first('password')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group">
                            <div>
                                <label for="passwordConfrim" class=" form-control-label">Konfirmasi Password</label>
                            </div>
                            <div>
                                <input type="password" name="passwordConfrim" placeholder="Password Confrim" class="form-control  {{$errors->has('passwordConfrim') ? 'form-control is-invalid' : 'form-control'}}" required>
                            </div>
                            @if ($errors->has('passwordConfrim'))
                            <span class="text-danger">
                                <strong id="textpasswordConfrim">{{ $errors->first('passwordConfrim')}}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group ">
                            <label for="rule">Hak Akses</label>
                            <select name="rule" class="selected2 form-control" id="cmbrule" required>
                                <option value="">--Pilih Hak Aksese--</option>
                                <option value="1" {{old('rule') == "1" ? "selected" : "" }}>Admin</option>
                                <option value="2" {{old('rule') == "2" ? "selected" : "" }}> Viewer</option>
                            </select>
                            @if ($errors->has('rule'))
                            <span class="text-danger">
                                <strong id="textrule">{{ $errors->first('rule')}}</strong>
                            </span>
                            @endif
                        </div>
                    </div>

                    <!-- /.card-body -->
                    <div class="card-footer clearfix">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->

    @stop

    @push('script')
    <script>
        $(function() {
            $("#nama").keypress(function() {
                $("#nama").removeClass("is-invalid");
                $("#textNama").html("");
            });
            $("#email").keypress(function() {
                $("#email").removeClass("is-invalid");
                $("#textemail").html("");
            });
            $("#password").keypress(function() {
                $("#password").removeClass("is-invalid");
                $("#textpassword").html("");
            });
            $("#password").keypress(function() {
                $("#password").removeClass("is-invalid");
                $("#textpassword").html("");
            });

            // $("#id_rt").keypress(function(){
            //   $("#id_rt").removeClass("is-invalid");
            //   $("#textid_rt").html("");
            // });
            $('#cmbrule').select2({
                placeholder: '--- Pilih Hak Akses ---',
                width: '100%'
            });

        });
    </script>
    @endpush

resources/views/user/edit.blade.php
@extends('template.app')

@section('content')

<div class="container-fluid">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{$title}}</h3>
                </div>
                <!-- /.card-header -->
                <form action="{{ $action }}" method="post" role="form" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="card-body">
                        <div class="form-group">
                            <div>
                                <label for="Name" class=" form-control-label">Name</label>
                            </div>
                            <div>
                                <input type="text" name="name" placeholder="Name User" class="form-control  {{$errors->has('name') ? 'form-control is-invalid' : 'form-control'}}" value="{{ $user->name }}" required>
                            </div>
                            @if ($errors->has('name'))
                            <div class=" container-fluid alert alert-warning alert-dismissible fade show" role="alert">
                                {{ $errors->first('name')}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            @endif
                        </div>
                        <div class="form-group">
                            <div>
                                <label for="email" class=" form-control-label">Email</label>
                            </div>
                            <div>
                                <input type="text" name="email" placeholder="email" class="form-control  {{$errors->has('email') ? 'form-control is-invalid' : 'form-control'}}" value="{{ $user->email }}" required>
                            </div>
                            @if ($errors->has('email'))
                            <div class=" container-fluid alert alert-warning alert-dismissible fade show" role="alert">
                                {{ $errors->first('email')}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            @endif
                        </div>

                        <div class="form-group">
                            <div>
                                <label for="passwordNew" class=" form-control-label">Password Baru</label>
                            </div>
                            <div>
                                <input type="password" name="passwordNew" placeholder="password Baru" class="form-control  {{$errors->has('passwordNew') ? 'form-control is-invalid' : 'form-control'}}">
                            </div>
                            @if ($errors->has('passwordNew'))
                            <div class=" container-fluid alert alert-warning alert-dismissible fade show" role="alert">
                                {{ $errors->first('passwordNew')}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            @endif
                        </div>
                        <div class="form-group">
                            <div>
                                <label for="passwordConfrim" class=" form-control-label">Password Confrim</label>
                            </div>
                            <div>
                                <input type="password" name="passwordConfrim" placeholder="Password Confrim" class="form-control  {{$errors->has('passwordConfrim') ? 'form-control is-invalid' : 'form-control'}}">
                            </div>
                            @if ($errors->has('passwordConfrim'))
                            <div class=" container-fluid alert alert-warning alert-dismissible fade show" role="alert">
                                {{ $errors->first('passwordConfrim')}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            @endif
                        </div>
                        <div class="form-group ">
                            <label for="rule">Hak Akses</label>
                            <select name="rule" class="selected2 form-control" id="cmbrule">
                                <option value="">--Pilih Hak Akses--</option>
                                <option value="1" {{$user->rule == "1" ? "selected" : ""}}>Admin</option>
                                <option value="2" {{$user->rule == "2" ? "selected" : ""}}>Viewer</option>
                            </select>
                            @if ($errors->has('rule'))
                            <span class="text-danger">
                                <strong id="textrule">Hak Akses salah</strong>
                            </span>
                            @endif
                        </div>
                    </div>

                    <!-- /.card-body -->
                    <div class="card-footer clearfix">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->

    @stop

    @push('script')
    <script>
        $(function() {
            $("#nama").keypress(function() {
                $("#nama").removeClass("is-invalid");
                $("#textNama").html("");
            });

            // $("#id_rt").keypress(function(){
            //   $("#id_rt").removeClass("is-invalid");
            //   $("#textid_rt").html("");
            // });
            $('#cmbrt').select2({
                placeholder: '--- Pilih RT ---',
                width: '100%'
            });
            $('#cmbrule').select2({
                placeholder: '--- Pilih Jabatan ---',
                width: '100%'
            });
        });
    </script>
    @endpush

resources/views/user/index.blade.php
@extends('template.app')

@section('content')

<div class="container-fluid">
  <!-- Small boxes (Stat box) -->
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Daftar {{$title}}</h3>
          <a href="{{route('user.create')}}" class="btn btn-sm btn-primary float-right text-light">
            <i class="fa fa-plus"></i>Tambah Data
          </a>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
          <table class="table table-bordered  table-responsive" width="100%">
            <thead>
              <tr>
                <th>#</th>
                <th>Nama</th>
                <th>Email</th>
                <th class="text-center" width="20%">Aksi</th>
              </tr>
            </thead>
            <tbody>
              @forelse ($dataUser as $index => $item)

              <tr>
                <td>{{ $index+1+(($dataUser->CurrentPage()-1)*$dataUser->PerPage()) }}</td>
                <td>{{$item->name}}</td>
                <td>{{$item->email}}</td>
                <td class="text-center">
                  <a href="{{route('user.edit',$item->id)}}" class="btn btn-sm btn-warning text-light">
                    <i class="nav-icon fas fa-edit"></i> Ubah</a>
                  <form id="form-{{$item->id}}" action="{{ route('user.destroy', $item->id)}}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                    {{method_field('DELETE')}}
                  </form>
                  <button class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Hapus" onclick=deleteconf("{{$item->id}}")>
                    <i class="fa fa-trash"></i> Hapus
                  </button>
                </td>
              </tr>
              @empty
              <tr>
                <td colspan="10">Data Pengguna tidak ada</td>
              </tr>
              @endforelse
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
        <div class="card-footer clearfix">
          {{ $dataUser->links() }}
        </div>
      </div>
      <!-- ./col -->
    </div>
    <!-- /.row -->
    <!-- Main row -->
    <!-- /.row (main row) -->
  </div><!-- /.container-fluid -->

  @stop

  @push('script')

  @endpush